### ISSUE TITLE
Release it

### ISSUE THREAD

**Issue by lyrixx** [marcw/silex-buzz-extension#4]
Can you tag this lib ? (easier with composer)

**Comment by lukaszwit** [comment]
If you tag it with stable version many peoples could use it otherwise it's just study case.

**Comment by lyrixx** [comment]
ho, I missed the anniversary of this issue;

![HB](http://www.freelargeimages.com/wp-content/uploads/2014/11/Happy_birthday-9.jpeg)

**Comment by marcw** [comment]
Didn't imagine it was still used... I'll tag it 1.0

**Comment by lukaszwit** [comment]
Thnx!

**Comment by marcw** [comment]
Tagged.
